version: '3.3'
services:
  couchdb:
    container_name: couchdb
    image: apache/couchdb:2.2.0
    restart: always
    ports:
      - 5984:5984
    expose:
      - '5984'
    environment:
      - 'COUCHDB_USER=fill-in'
      - 'COUCHDB_PASSWORD=fill-in'
